import pandas as pd

# excel reading command(your excel document should be in same folder with code)
df = pd.read_excel("write_file_name_here.xlsx")

for column in df.columns:
    # Changing russian letters to latin
    df[column] = df[column].str.replace(r'А', "A")
    df[column] = df[column].str.replace(r'В', "V")
    df[column] = df[column].str.replace(r'Г', "G")
    df[column] = df[column].str.replace(r'Д', "D")
    df[column] = df[column].str.replace(r'Е', "E")
    df[column] = df[column].str.replace(r'Ё', "Yo")
    df[column] = df[column].str.replace(r'Ж', "Zh")
    df[column] = df[column].str.replace(r'З', "Z")
    df[column] = df[column].str.replace(r'И', "I")
    df[column] = df[column].str.replace(r'Й', "Y")
    df[column] = df[column].str.replace(r'К', "K")
    df[column] = df[column].str.replace(r'Л', "L")
    df[column] = df[column].str.replace(r'М', "M")
    df[column] = df[column].str.replace(r'Н', "N")
    df[column] = df[column].str.replace(r'О', "O")
    df[column] = df[column].str.replace(r'П', "P")
    df[column] = df[column].str.replace(r'Р', "R")
    df[column] = df[column].str.replace(r'С', "S")
    df[column] = df[column].str.replace(r'Т', "T")
    df[column] = df[column].str.replace(r'У', "U")
    df[column] = df[column].str.replace(r'Ф', "F")
    df[column] = df[column].str.replace(r'Х', "Kh")
    df[column] = df[column].str.replace(r'Ц', "Ts")
    df[column] = df[column].str.replace(r'Ч', "Ch")
    df[column] = df[column].str.replace(r'Ш', "Sh")
    df[column] = df[column].str.replace(r'Щ', "Sch")
    df[column] = df[column].str.replace(r'Ы', "I")
    df[column] = df[column].str.replace(r'Э', "E")
    df[column] = df[column].str.replace(r'Ю', "Yu")
    df[column] = df[column].str.replace(r'Я', "Ya")

    df[column] = df[column].str.replace(r'а', "a")
    df[column] = df[column].str.replace(r'б', "b")
    df[column] = df[column].str.replace(r'в', "v")
    df[column] = df[column].str.replace(r'г', "g")
    df[column] = df[column].str.replace(r'д', "d")
    df[column] = df[column].str.replace(r'е', "e")
    df[column] = df[column].str.replace(r'ё', "yo")
    df[column] = df[column].str.replace(r'ж', "zh")
    df[column] = df[column].str.replace(r'з', "z")
    df[column] = df[column].str.replace(r'и', "i")
    df[column] = df[column].str.replace(r'й', "y")
    df[column] = df[column].str.replace(r'к', "k")
    df[column] = df[column].str.replace(r'л', "l")
    df[column] = df[column].str.replace(r'м', "m")
    df[column] = df[column].str.replace(r'н', "n")
    df[column] = df[column].str.replace(r'о', "o")
    df[column] = df[column].str.replace(r'п', "p")
    df[column] = df[column].str.replace(r'р', "r")
    df[column] = df[column].str.replace(r'с', "s")
    df[column] = df[column].str.replace(r'т', "t")
    df[column] = df[column].str.replace(r'у', "u")
    df[column] = df[column].str.replace(r'ф', "f")
    df[column] = df[column].str.replace(r'х', "kh")
    df[column] = df[column].str.replace(r'ц', "ts")
    df[column] = df[column].str.replace(r'ч', "ch")
    df[column] = df[column].str.replace(r'ш', "sh")
    df[column] = df[column].str.replace(r'щ', "sch")
    df[column] = df[column].str.replace(r'ъ', "")
    df[column] = df[column].str.replace(r'ы', "i")
    df[column] = df[column].str.replace(r'ь', "")
    df[column] = df[column].str.replace(r'э', "e")
    df[column] = df[column].str.replace(r'ю', "yu")
    df[column] = df[column].str.replace(r'я', "ya")

# saving new excel file
df.to_excel("changed_excel.xlsx")
